name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PROJECT: 'HealthCareClinic/Hospital/Hospital.csproj'
      TEST: 'HealthCareClinic/HospitalTests/HospitalTests.csproj'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Display the path
      run: echo $PATH
      shell: bash
    - name: Restore dependencies
      run: dotnet restore $PROJECT
    - name: Build
      run: dotnet build $PROJECT --no-restore
    - name: Test
      run: dotnet test $TEST --no-build --verbosity normal
