name: .NET
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT: 'HealthCareClinic/Hospital/Hospital.csproj'
      TEST: 'HealthCareClinic/HospitalTests/HospitalTests.csproj'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore $PROJECT
    - name: Build
      run: dotnet build $PROJECT --no-restore
    - name: Test
      run: dotnet test $TEST --logger trx --no-build --verbosity normal
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: test-results/**/*.xml
